# Generated by Django 4.2.1 on 2023-06-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprimaria', '0002_tema_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='nivel',
        ),
        migrations.AddField(
            model_name='tema',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vistaprimaria.nivel'),
        ),
    ]
