# Generated by Django 4.2.1 on 2023-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprimaria', '0003_remove_tema_nivel_tema_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tema/%Y/%m/%d'),
        ),
    ]
