# Generated by Django 4.2.1 on 2023-07-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprimaria', '0005_continente_remove_tema_nivel_delete_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='continente',
        ),
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoca', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='epoca/%Y/%m/%d')),
                ('continente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vistaprimaria.continente')),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='epoca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vistaprimaria.epoca'),
        ),
    ]
