# Generated by Django 4.2.1 on 2023-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprimaria', '0006_remove_tema_continente_epoca_tema_epoca'),
    ]

    operations = [
        migrations.AddField(
            model_name='continente',
            name='descripcion',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='epoca',
            name='descripcion',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tema',
            name='descripcion',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
